// create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "name" : "nabilla",
  "email": "nabilla@gmail.com",
  "password" : "snaggle",
  "confPassword": "snaggle",
  "role": "user"
}

###
// get All User
GET http://localhost:5000/users


###
// get Single User
GET http://localhost:5000/users/dae71a8b-9cd8-485c-9221-56b2783acdf6

###
// Update User
PATCH  http://localhost:5000/users/dae71a8b-9cd8-485c-9221-56b2783acdf6
Content-Type: application/json

{
  "name" : "Nabilla Updated",
  "email": "nabilla@gmail.com",
  "password" : "",
  "confPassword": ""
}

###
// delete User
DELETE   http://localhost:5000/users/ba22b6e9-0643-40ac-affd-cc6877916152

###
// login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "nabilla@gmail.com",
  "password" : "snaggle"
}

###
GET http://localhost:5000/me

###
DELETE  http://localhost:5000/logout

###
// login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "nathan@gmail.com",
  "password" : "snaggle"
}

###
// get All Category
GET http://localhost:5000/category

###
// get Single Category
GET http://localhost:5000/category/00c1f686-2eca-42d9-9f86-482b38df7502

###
// post Data Category
POST http://localhost:5000/category
Content-Type: application/json

{
  "name": "Kemeja"
}

###
// post Data Category
PATCH  http://localhost:5000/category/f24ea77e-a547-418c-b5e7-e0322cdefbf7
Content-Type: application/json

{
  "name": "Dress"
}

###
// Delete Data Category
DELETE   http://localhost:5000/category/f24ea77e-a547-418c-b5e7-e0322cdefbf7

###
// post Data Category
POST http://localhost:5000/product
Content-Type: application/json

{
  "name": "Kemeja Panjang",
  "description": "sawerwr",
  "price": 100000,
  "status": "tersedia",
  "categoryId":"1"
}

###
// post Data Category
PATCH http://localhost:5000/recoveryPassword
Content-Type: application/json

{
  "email": "nabilla@gmail.com",
  "password": "snaggle",
  "newPassword": "well",
  "confPassword": "well"
}